endpoints:
  restart:
    enabled: true

spring:
  application:
   name: config-service
  cloud:
   config:
      uri: https://github.com/Merdoc97/springcloudtest/tree/master/configserver/src/main/resources/configuration
      fail-fast: true