spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Merdoc97/config-repo

  application:
    name: configserver

eureka:
  instance:
    hostname: localhost
  client:
   registerWithEureka: true
   fetchRegistry: true
   serviceUrl:
     defaultZone: http://localhost:1111/eureka/

server:
  port: 2228