server:
  port: 2224
spring:
  application:
   name: zuul-router

zuul:
 routes:
  example:
   stripPrefix: true

  ribbon:
    eureka:
       enabled: false
    serverListRefreshInterval: 5

eureka:
  client:
   serviceUrl:
     defaultZone: http://localhost:1111/eureka/
   dashboard:
     enabled: false

